blank_issues_enabled: true
contact_links:
  - name: Inch Worm Games Community 
    url: https://github.com/inch-worm-games/inch-worm-games/discussions
    about: Check out our amazing community!
  - name: Inch Worm Games Contact 
    url: contact@inchworm.games
    about: Feel free to reach out!
